import 'dart:io';
import 'dart:ui' as ui;
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:file_saver/file_saver.dart';

class ExportHelper {
  static Future<void> showExportDialog({
    required BuildContext context,
    required GlobalKey boundaryKey,
    required String fileName,
  }) async {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (context) {
        return SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Text('Choose Export Format', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                const SizedBox(height: 16),
                ListTile(
                  leading: const Icon(Icons.image, color: Colors.blue),
                  title: const Text('Export as PNG'),
                  onTap: () {
                    Navigator.pop(context);
                    exportBoundary(context: context, key: boundaryKey, fileName: fileName, ext: 'png', isShare: true);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.picture_as_pdf, color: Colors.blueAccent),
                  title: const Text('Export as PDF (Share)'),
                  onTap: () {
                    Navigator.pop(context);
                    exportPDF(context: context, key: boundaryKey, fileName: fileName, isShare: true);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.save_alt, color: Colors.green),
                  title: const Text('Save Local (PNG)'),
                  onTap: () {
                    Navigator.pop(context);
                    exportBoundary(context: context, key: boundaryKey, fileName: fileName, ext: 'png', isShare: false);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.picture_as_pdf, color: Colors.green),
                  title: const Text('Save Local (PDF)'),
                  onTap: () {
                    Navigator.pop(context);
                    exportPDF(context: context, key: boundaryKey, fileName: fileName, isShare: false);
                  },
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  static Future<void> exportBoundary({
    required BuildContext context,
    required GlobalKey key,
    required String fileName,
    required String ext,
    required bool isShare,
  }) async {
    try {
      RenderRepaintBoundary boundary = key.currentContext!.findRenderObject() as RenderRepaintBoundary;
      ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      Uint8List pngBytes = byteData!.buffer.asUint8List();

      if (isShare) {
        final directory = await getTemporaryDirectory();
        final File imgFile = File('${directory.path}/${fileName}_${DateTime.now().millisecondsSinceEpoch}.$ext');
        await imgFile.writeAsBytes(pngBytes);

        if (context.mounted) {
          final box = context.findRenderObject() as RenderBox?;
          await SharePlus.instance.share(
            ShareParams(
              files: [XFile(imgFile.path)],
              text: 'Generated by SmartScan App',
              sharePositionOrigin: box != null ? box.localToGlobal(Offset.zero) & box.size : null,
            ),
          );
        }
      } else {
        String? savedPath = await FileSaver.instance.saveAs(
          name: '${fileName}_${DateTime.now().millisecondsSinceEpoch}',
          bytes: pngBytes,
          fileExtension: ext,
          mimeType: ext.toLowerCase() == 'png' ? MimeType.png : MimeType.custom,
        );
        if (context.mounted && savedPath != null && savedPath.isNotEmpty) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('File saved successfully!')),
          );
        }
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  static Future<void> exportPDF({
    required BuildContext context,
    required GlobalKey key,
    required String fileName,
    required bool isShare,
  }) async {
    try {
      RenderRepaintBoundary boundary = key.currentContext!.findRenderObject() as RenderRepaintBoundary;
      ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      Uint8List pngBytes = byteData!.buffer.asUint8List();

      final pdf = pw.Document();
      final pdfImage = pw.MemoryImage(pngBytes);
      
      pdf.addPage(
        pw.Page(
          build: (pw.Context context) {
            return pw.Center(child: pw.Image(pdfImage));
          },
        ),
      );

      final Uint8List pdfBytes = await pdf.save();

      if (isShare) {
        final directory = await getTemporaryDirectory();
        final File pdfFile = File('${directory.path}/${fileName}_${DateTime.now().millisecondsSinceEpoch}.pdf');
        await pdfFile.writeAsBytes(pdfBytes);

        if (context.mounted) {
          final box = context.findRenderObject() as RenderBox?;
          await SharePlus.instance.share(
            ShareParams(
              files: [XFile(pdfFile.path)],
              text: 'Generated by SmartScan App',
              sharePositionOrigin: box != null ? box.localToGlobal(Offset.zero) & box.size : null,
            ),
          );
        }
      } else {
        String? savedPath = await FileSaver.instance.saveAs(
          name: '${fileName}_${DateTime.now().millisecondsSinceEpoch}',
          bytes: pdfBytes,
          fileExtension: 'pdf',
          mimeType: MimeType.pdf,
        );
        if (context.mounted && savedPath != null && savedPath.isNotEmpty) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('PDF saved successfully!')),
          );
        }
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }
}
