import 'dart:io';
import 'dart:ui' as ui;
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:file_saver/file_saver.dart';
import 'dart:convert';
import 'package:qr/qr.dart';

class ExportHelper {
  static Future<void> showExportDialog({
    required BuildContext context,
    required GlobalKey boundaryKey,
    required String fileName,
  }) async {
    showModalBottomSheet(
      context: context,
      shape: const RoundedRectangleBorder(borderRadius: BorderRadius.vertical(top: Radius.circular(20))),
      builder: (context) {
        return SafeArea(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const Text('Choose Export Format', style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
                const SizedBox(height: 16),
                ListTile(
                  leading: const Icon(Icons.image, color: Colors.blue),
                  title: const Text('Export as PNG'),
                  onTap: () {
                    Navigator.pop(context);
                    exportBoundary(context: context, key: boundaryKey, fileName: fileName, ext: 'png', isShare: true);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.picture_as_pdf, color: Colors.blueAccent),
                  title: const Text('Export as PDF (Share)'),
                  onTap: () {
                    Navigator.pop(context);
                    exportPDF(context: context, key: boundaryKey, fileName: fileName, isShare: true);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.save_alt, color: Colors.green),
                  title: const Text('Save Local (PNG)'),
                  onTap: () {
                    Navigator.pop(context);
                    exportBoundary(context: context, key: boundaryKey, fileName: fileName, ext: 'png', isShare: false);
                  },
                ),
                ListTile(
                  leading: const Icon(Icons.picture_as_pdf, color: Colors.green),
                  title: const Text('Save Local (PDF)'),
                  onTap: () {
                    Navigator.pop(context);
                    exportPDF(context: context, key: boundaryKey, fileName: fileName, isShare: false);
                  },
                ),
              ],
            ),
          ),
        );
      },
    );
  }

  static Future<void> exportBoundary({
    required BuildContext context,
    required GlobalKey key,
    required String fileName,
    required String ext,
    required bool isShare,
  }) async {
    try {
      RenderRepaintBoundary boundary = key.currentContext!.findRenderObject() as RenderRepaintBoundary;
      ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      Uint8List pngBytes = byteData!.buffer.asUint8List();

      // For JPEG, we still capture as PNG (Flutter limitation) but save with .jpeg extension
      final String actualExt = ext.toLowerCase() == 'jpeg' ? 'jpeg' : ext;
      final MimeType mimeType = actualExt == 'jpeg' ? MimeType.custom : MimeType.png;

      if (isShare) {
        final directory = await getTemporaryDirectory();
        final File imgFile = File('${directory.path}/${fileName}_${DateTime.now().millisecondsSinceEpoch}.$actualExt');
        await imgFile.writeAsBytes(pngBytes);

        if (context.mounted) {
          final box = context.findRenderObject() as RenderBox?;
          await SharePlus.instance.share(
            ShareParams(
              files: [XFile(imgFile.path)],
              text: 'Generated by SmartScan App',
              sharePositionOrigin: box != null ? box.localToGlobal(Offset.zero) & box.size : null,
            ),
          );
        }
      } else {
        String? savedPath = await FileSaver.instance.saveAs(
          name: '${fileName}_${DateTime.now().millisecondsSinceEpoch}',
          bytes: pngBytes,
          fileExtension: actualExt,
          mimeType: mimeType,
        );
        if (context.mounted && savedPath != null && savedPath.isNotEmpty) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(content: Text('File saved as ${actualExt.toUpperCase()} successfully!')),
          );
        }
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  static Future<void> exportPDF({
    required BuildContext context,
    required GlobalKey key,
    required String fileName,
    required bool isShare,
  }) async {
    try {
      RenderRepaintBoundary boundary = key.currentContext!.findRenderObject() as RenderRepaintBoundary;
      ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      ByteData? byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      Uint8List pngBytes = byteData!.buffer.asUint8List();

      final pdf = pw.Document();
      final pdfImage = pw.MemoryImage(pngBytes);
      
      pdf.addPage(
        pw.Page(
          build: (pw.Context context) {
            return pw.Center(child: pw.Image(pdfImage));
          },
        ),
      );

      final Uint8List pdfBytes = await pdf.save();

      if (isShare) {
        final directory = await getTemporaryDirectory();
        final File pdfFile = File('${directory.path}/${fileName}_${DateTime.now().millisecondsSinceEpoch}.pdf');
        await pdfFile.writeAsBytes(pdfBytes);

        if (context.mounted) {
          final box = context.findRenderObject() as RenderBox?;
          await SharePlus.instance.share(
            ShareParams(
              files: [XFile(pdfFile.path)],
              text: 'Generated by SmartScan App',
              sharePositionOrigin: box != null ? box.localToGlobal(Offset.zero) & box.size : null,
            ),
          );
        }
      } else {
        String? savedPath = await FileSaver.instance.saveAs(
          name: '${fileName}_${DateTime.now().millisecondsSinceEpoch}',
          bytes: pdfBytes,
          fileExtension: 'pdf',
          mimeType: MimeType.pdf,
        );
        if (context.mounted && savedPath != null && savedPath.isNotEmpty) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('PDF saved successfully!')),
          );
        }
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  /// Export QR data as SVG file
  static Future<void> exportSVG({
    required BuildContext context,
    required String qrData,
    required String fileName,
  }) async {
    try {
      // Generate a simple SVG QR code representation
      final svgContent = _generateQrSvg(qrData);
      final Uint8List svgBytes = Uint8List.fromList(utf8.encode(svgContent));

      final directory = await getTemporaryDirectory();
      final File svgFile = File('${directory.path}/${fileName}_${DateTime.now().millisecondsSinceEpoch}.svg');
      await svgFile.writeAsBytes(svgBytes);

      if (context.mounted) {
        final box = context.findRenderObject() as RenderBox?;
        await SharePlus.instance.share(
          ShareParams(
            files: [XFile(svgFile.path)],
            text: 'Generated by SmartScan App',
            sharePositionOrigin: box != null ? box.localToGlobal(Offset.zero) & box.size : null,
          ),
        );
      }
    } catch (e) {
      if (context.mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
      }
    }
  }

  /// Generates a proper vector SVG QR code using the qr package.
  static String _generateQrSvg(String qrData) {
    final qrCode = QrCode.fromData(
      data: qrData,
      errorCorrectLevel: QrErrorCorrectLevel.M,
    );
    final qrImage = QrImage(qrCode);
    final moduleCount = qrCode.moduleCount;
    final margin = 4;
    final size = moduleCount + margin * 2;

    final buffer = StringBuffer();
    buffer.writeln('<?xml version="1.0" encoding="UTF-8"?>');
    buffer.writeln('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 $size $size" width="256" height="256">');
    buffer.writeln('  <rect width="$size" height="$size" fill="white"/>');

    for (int x = 0; x < moduleCount; x++) {
      for (int y = 0; y < moduleCount; y++) {
        if (qrImage.isDark(y, x)) {
          buffer.writeln('  <rect x="${x + margin}" y="${y + margin}" width="1" height="1" fill="black"/>');
        }
      }
    }

    buffer.writeln('</svg>');
    return buffer.toString();
  }
}
