import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/locale_provider.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'SmartScan',
      'qr_generator': 'QR Generator',
      'qr_short': 'QR',
      'barcode_generator': 'Barcode Generator',
      'barcode_short': 'Barcode',
      'scanner': 'Scanner',
      'settings': 'Settings',
      'language': 'Language',
      'batch_generation': 'Batch Generation',
      'history': 'History',
      'history_empty': 'No history yet.',
      'choose_format': 'Choose Format',
      'export': 'Export',
      'share': 'Share',
      'save': 'Save',
      'copy': 'Copy',
      'content_type': 'Content Type',
      'pick_logo': 'Pick Logo',
      'colors': 'Colors & Shapes',
      'dark_mode': 'Dark Mode',
      'barcode_input_hint': 'Enter text or numbers...',
      'batch_instructions': 'Upload a CSV or Excel (.xlsx) file.\nThe first column will be used to generate QR codes.\nAll codes will be exported as a ZIP file.',
      'select_file': 'Select CSV or Excel File',
      'items_found': 'items found',
      'preview': 'Preview:',
      'more_items': 'more items',
      'generate': 'Generate',
      'cannot_open_link': 'Problem opening link',
    },
    'ar': {
      'app_name': 'سمارت سكان',
      'qr_generator': 'إنشاء QR',
      'qr_short': 'QR',
      'barcode_generator': 'إنشاء باركود',
      'barcode_short': 'باركود',
      'scanner': 'الماسح الضوئي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'batch_generation': 'توليد بالجملة',
      'history': 'السجل',
      'history_empty': 'لا يوجد سجل حتى الآن.',
      'choose_format': 'اختر الصيغة',
      'export': 'تصدير',
      'share': 'مشاركة',
      'save': 'حفظ',
      'copy': 'نسخ',
      'content_type': 'نوع المحتوى',
      'pick_logo': 'اختيار شعار',
      'colors': 'الألوان والأشكال',
      'dark_mode': 'الوضع الليلي',
      'barcode_input_hint': 'أدخل نصاً أو أرقاماً...',
      'batch_instructions': 'ارفع ملف CSV أو Excel (.xlsx).\nسيتم استخدام العمود الأول لتوليد أكواد QR.\nسيتم تصدير جميع الأكواد في ملف ZIP.',
      'select_file': 'اختر ملف CSV أو Excel',
      'items_found': 'عنصر تم العثور عليه',
      'preview': 'معاينة:',
      'more_items': 'عناصر إضافية',
      'generate': 'توليد',
      'cannot_open_link': 'تعذر فتح الرابط',
    },
    'fr': {
      'app_name': 'SmartScan',
      'qr_generator': 'Générer QR',
      'qr_short': 'QR',
      'barcode_generator': 'Générer Code-barres',
      'barcode_short': 'Barcode',
      'scanner': 'Scanner',
      'settings': 'Paramètres',
      'language': 'Langue',
      'batch_generation': 'Génération par Lot',
      'history': 'Historique',
      'history_empty': 'Aucun historique.',
      'choose_format': 'Choisissez le Format',
      'export': 'Exporter',
      'share': 'Partager',
      'save': 'Enregistrer',
      'copy': 'Copier',
      'content_type': 'Type de contenu',
      'pick_logo': 'Choisir Logo',
      'colors': 'Couleurs et Formes',
      'dark_mode': 'Mode Sombre',
      'barcode_input_hint': 'Entrez du texte ou des chiffres...',
      'batch_instructions': 'Importez un fichier CSV ou Excel (.xlsx).\nLa première colonne sera utilisée pour générer les QR codes.\nTous les codes seront exportés dans un fichier ZIP.',
      'select_file': 'Sélectionner un fichier CSV ou Excel',
      'items_found': 'éléments trouvés',
      'preview': 'Aperçu :',
      'more_items': 'éléments supplémentaires',
      'generate': 'Générer',
      'cannot_open_link': 'Problème d\'ouverture du lien',
    },
  };

  static String of(BuildContext context, String key) {
    final locale = Provider.of<LocaleProvider>(context).locale.languageCode;
    return _localizedValues[locale]?[key] ?? key;
  }
}
