import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../providers/locale_provider.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'SmartScan',
      'qr_generator': 'QR Generator',
      'qr_short': 'QR',
      'barcode_generator': 'Barcode Generator',
      'barcode_short': 'Barcode',
      'scanner': 'Scanner',
      'settings': 'Settings',
      'language': 'Language',
      'batch_generation': 'Batch Generation',
      'history': 'History',
      'history_empty': 'No history yet.',
      'choose_format': 'Choose Format',
      'export': 'Export',
      'share': 'Share',
      'save': 'Save',
      'copy': 'Copy',
      'content_type': 'Content Type',
      'pick_logo': 'Pick Logo',
      'colors': 'Colors & Shapes',
      'dark_mode': 'Dark Mode',
      'barcode_input_hint': 'Enter text or numbers...',
      'batch_instructions': 'Upload a CSV or Excel (.xlsx) file.\nThe first column will be used to generate QR codes.\nAll codes will be exported as a ZIP file.',
      'select_file': 'Select CSV or Excel File',
      'items_found': 'items found',
      'preview': 'Preview:',
      'more_items': 'more items',
      'generate': 'Generate',
      'cannot_open_link': 'Problem opening link',
      'clear': 'Clear',
      'export_as_png': 'Export as PNG',
      'export_as_pdf': 'Export as PDF (Share)',
      'save_local_png': 'Save Local (PNG)',
      'save_local_pdf': 'Save Local (PDF)',
      'no_qr_found': 'No QR/Barcode found in image.',
      'copied': 'Copied to clipboard',
      'open': 'Open',
      'close': 'Close',
      'qr_code': 'QR Code',
      'barcode_label': 'Barcode',
      'eye_shape': 'Eye Shape',
      'square_eyes': 'Square Eyes',
      'round_eyes': 'Round Eyes',
      'qr_size': 'QR Code Size',
      'download_format': 'Download Format',
      'no_valid_data': 'No valid data found in the file.',
      'switch_camera': 'Switch Camera',
      'csv_support': 'CSV/Excel Support',
      'numeric_warning': 'Please ensure your file contains valid numbers for ',
      'delete_selected': 'Delete Selected',
      'copy_password': 'Copy Password',
      'add_contact': 'Add Contact',
      'send_email': 'Send Email',
      'send_sms': 'Send SMS',
      'open_map': 'Open Map',
      'batch_column_note': 'Note: Ensure your data is in the first column (Column A).',
      'update_available': 'New Update Available',
      'version': 'Version',
      'update_later': 'Later',
      'update_now': 'Update Now',
      'clear_history_title': 'Clear History',
      'clear_history_msg': 'Are you sure you want to clear all history? This action cannot be undone.',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'batch_empty_title': 'No File Selected',
      'batch_empty_msg': 'Upload a CSV or Excel file to start generating barcodes in bulk.',
      'batch_upload_cta': 'Upload your first file',
    },
    'ar': {
      'app_name': 'سمارت سكان',
      'qr_generator': 'إنشاء QR',
      'qr_short': 'QR',
      'barcode_generator': 'إنشاء باركود',
      'barcode_short': 'باركود',
      'scanner': 'الماسح الضوئي',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'batch_generation': 'توليد بالجملة',
      'history': 'السجل',
      'history_empty': 'لا يوجد سجل حتى الآن.',
      'choose_format': 'اختر الصيغة',
      'export': 'تصدير',
      'share': 'مشاركة',
      'save': 'حفظ',
      'copy': 'نسخ',
      'content_type': 'نوع المحتوى',
      'pick_logo': 'اختيار شعار',
      'colors': 'الألوان والأشكال',
      'dark_mode': 'الوضع الليلي',
      'barcode_input_hint': 'أدخل نصاً أو أرقاماً...',
      'batch_instructions': 'ارفع ملف CSV أو Excel (.xlsx).\nسيتم استخدام العمود الأول لتوليد أكواد QR.\nسيتم تصدير جميع الأكواد في ملف ZIP.',
      'select_file': 'اختر ملف CSV أو Excel',
      'items_found': 'عنصر تم العثور عليه',
      'preview': 'معاينة:',
      'more_items': 'عناصر إضافية',
      'generate': 'توليد',
      'cannot_open_link': 'تعذر فتح الرابط',
      'clear': 'مسح',
      'export_as_png': 'تصدير كـ PNG',
      'export_as_pdf': 'تصدير كـ PDF (مشاركة)',
      'save_local_png': 'حفظ محلي (PNG)',
      'save_local_pdf': 'حفظ محلي (PDF)',
      'numeric_warning': 'يرجى التأكد من أن ملفك يحتوي على أرقام صالحة لـ ',
      'no_qr_found': 'لم يتم العثور على QR/باركود في الصورة.',
      'copied': 'تم النسخ إلى الحافظة',
      'open': 'فتح',
      'close': 'إغلاق',
      'qr_code': 'رمز QR',
      'barcode_label': 'باركود',
      'eye_shape': 'شكل العين',
      'square_eyes': 'عيون مربعة',
      'round_eyes': 'عيون دائرية',
      'qr_size': 'حجم رمز QR',
      'download_format': 'صيغة التحميل',
      'no_valid_data': 'لم يتم العثور على بيانات صالحة في الملف.',
      'switch_camera': 'تبديل الكاميرا',
      'csv_support': 'دعم CSV/Excel',
      'delete_selected': 'حذف المحدد',
      'copy_password': 'نسخ كلمة المرور',
      'add_contact': 'إضافة جهة اتصال',
      'send_email': 'إرسال بريد',
      'send_sms': 'إرسال رسالة',
      'open_map': 'فتح الخريطة',
      'batch_column_note': 'ملاحظة: تأكد من وضع البيانات في العمود الأول (العمود A).',
      'update_available': 'تحديث جديد متوفر',
      'version': 'الإصدار',
      'update_later': 'لاحقاً',
      'update_now': 'تحديث الآن',
      'clear_history_title': 'مسح السجل',
      'clear_history_msg': 'هل أنت متأكد من أنك تريد مسح السجل بالكامل؟ لا يمكن التراجع عن هذا الإجراء.',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'batch_empty_title': 'لم يتم اختيار ملف',
      'batch_empty_msg': 'ارفع ملف CSV أو Excel للبدء في توليد الباركود بالجملة.',
      'batch_upload_cta': 'ارفع ملفك الأول',
    },
    'fr': {
      'app_name': 'SmartScan',
      'qr_generator': 'Générer QR',
      'qr_short': 'QR',
      'barcode_generator': 'Générer Code-barres',
      'barcode_short': 'Barcode',
      'scanner': 'Scanner',
      'settings': 'Paramètres',
      'language': 'Langue',
      'batch_generation': 'Génération par Lot',
      'history': 'Historique',
      'history_empty': 'Aucun historique.',
      'choose_format': 'Choisissez le Format',
      'export': 'Exporter',
      'share': 'Partager',
      'save': 'Enregistrer',
      'copy': 'Copier',
      'content_type': 'Type de contenu',
      'pick_logo': 'Choisir Logo',
      'colors': 'Couleurs et Formes',
      'dark_mode': 'Mode Sombre',
      'barcode_input_hint': 'Entrez du texte ou des chiffres...',
      'batch_instructions': 'Importez un fichier CSV ou Excel (.xlsx).\nLa première colonne sera utilisée pour générer les QR codes.\nTous les codes seront exportés dans un fichier ZIP.',
      'select_file': 'Sélectionner un fichier CSV ou Excel',
      'items_found': 'éléments trouvés',
      'preview': 'Aperçu :',
      'more_items': 'éléments supplémentaires',
      'generate': 'Générer',
      'cannot_open_link': 'Problème d\'ouverture du lien',
      'clear': 'Effacer',
      'export_as_png': 'Exporter en PNG',
      'export_as_pdf': 'Exporter en PDF (Partager)',
      'save_local_png': 'Sauvegarder local (PNG)',
      'save_local_pdf': 'Sauvegarder local (PDF)',
      'numeric_warning': 'Veuillez vous assurer que le fichier contient des chiffres valides pour ',
      'no_qr_found': 'Aucun QR/Code-barres trouvé dans l\'image.',
      'copied': 'Copié dans le presse-papiers',
      'open': 'Ouvrir',
      'close': 'Fermer',
      'qr_code': 'Code QR',
      'barcode_label': 'Code-barres',
      'eye_shape': 'Forme des yeux',
      'square_eyes': 'Yeux carrés',
      'round_eyes': 'Yeux ronds',
      'qr_size': 'Taille du code QR',
      'download_format': 'Format de téléchargement',
      'no_valid_data': 'Aucune donnée valide trouvée dans le fichier.',
      'switch_camera': 'Changer de caméra',
      'csv_support': 'Support CSV/Excel',
      'delete_selected': 'Supprimer la sélection',
      'copy_password': 'Copier le mot de passe',
      'add_contact': 'Ajouter le contact',
      'send_email': 'Envoyer un email',
      'send_sms': 'Envoyer un SMS',
      'open_map': 'Ouvrir la carte',
      'batch_column_note': 'Remarque : Assurez-vous que vos données se trouvent dans la première colonne (Colonne A).',
      'update_available': 'Mise à jour disponible',
      'version': 'Version',
      'update_later': 'Plus tard',
      'update_now': 'Mettre à jour maintenant',
      'clear_history_title': 'Effacer l\'historique',
      'clear_history_msg': 'Voulez-vous vraiment effacer tout l\'historique ? Cette action est irréversible.',
      'confirm': 'Confirmer',
      'cancel': 'Annuler',
      'batch_empty_title': 'Aucun fichier sélectionné',
      'batch_empty_msg': 'Importez un fichier CSV ou Excel pour commencer à générer des codes-barres en masse.',
      'batch_upload_cta': 'Importer votre premier fichier',
    },
  };

  static String of(BuildContext context, String key) {
    final locale = Provider.of<LocaleProvider>(context).locale.languageCode;
    return _localizedValues[locale]?[key] ?? key;
  }
}
